name: Deploy to DigitalOcean

# This action runs on every push to the main branch
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into Droplet and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
          # Navigate to your project directory
          cd /var/www/portfolio_creator

          # CRITICAL FIX: Discard any local changes on the server
          echo "Resetting local repository to match GitHub..."
          git reset --hard origin/master

          # Pull the latest changes from the master branch
          echo "Pulling latest code from GitHub..."
          git pull origin master

          # Install backend dependencies and restart the application with PM2
          echo "Deploying backend..."
          cd Backend
          npm install
          pm2 restart backend
          pm2 save
          
          # Build and deploy the frontend application
          echo "Deploying frontend..."
          cd ../Frontend
          npm install
          npm run build
          sudo cp -r dist/* /var/www/your-frontend/

          # Restart Nginx to apply changes
          echo "Restarting Nginx..."
          sudo systemctl restart nginx

          echo "Deployment finished successfully!"
